### ISSUE TITLE
mcjoin (receiver) not receiving the multicast packet

### ISSUE THREAD

**Issue by dkoh703** [troglobit/mcjoin#17]
Hi, 

I'm trying to run the mcjoin on RHEL 7.4 in GNS3 and from the RHEL, I run tcpdump and can see the udp packet from the sender. However the mcjoin program shows 0 packets. Is there anything I missed? 

Sender:  mcjoin -s -t 100 -p 50500
Receiver: mcjoin -p 50500

**Comment by troglobit** [comment]
To answer that I need to know more in detail how your topology looks. From where are you running the sender, how does it connect to the receiver, and where did you run tcpdump?

**Comment by dkoh703** [comment]
Hi, 
The topology is as below:

sender VM <--> R1 <--> R2 (RP) <--> receiver VM

R1 and R2 configured with PIM, multicast routing and OSPF enabled.
R2 is the Rendezvous Point with RP address 192.168.1.25 (loopback)

I run the tcpdump on the receiver VM ethernet interface "ens3" and on the R2 egress interface to receiver VM. I can see the udp packet on both tcpdump output.

**Comment by troglobit** [comment]
OK, sorry for the twenty questions, many users asking questions don't have their ducks in a row.  From your setup I can tell you it's very similar to how I test myself, without any problem.  So  I googled RHEL, since I never use it myself, and there it is: Linux 3.10.0-nnn.  There's been very odd problems with older kernels that I've never really had the time to get to the bottom of.  A colleague of mine ran into a similar issue a couple of weeks back, IIRC it was Ubuntu 16.04 with Linux 4.4.x, which is a fairly recent kernel, but even that failed.  Sorry.

**Comment by troglobit** [comment]
Spent a few hours today testing mcjoin on both CentOS 7 and 8, with no luck whatsoever! Unfortunately I have no idea what the problem is.  Even tested with sender and receiver on same LAN, still nothing could be received, despite tcpdump seeing every packet on the receiving interface.  

I'm giving up, maybe someone else have an idea what's going on with RHEL/CentOS.

**Comment by dkoh703** [comment]
Thanks for spending time to test it out. May I know which OS that was working in your test?

**Comment by troglobit** [comment]
Really frustrating, but not even the most basic multicast receiver program works (open socket, add membership, recv()).

Iirc, yesterday was spent on testing CentOS versions and Debian.  The others are from memory:
 - Linux Mint 20.x
 - Ubuntu 18.04 (or 18.10) and later
 - Debian 8/9/10 and later
 - Alpine Linux 3.10 and later

What seems to be a common denominator is Linux 4.19 or later.

**Comment by dkoh703** [comment]
Ok, at least now I can confirm the issue is on the RHEL not on my network config. Thanks for testing it out.

**Comment by dkoh703** [comment]
Tested on Ubuntu 18.x and it's working. Closing this issue.
